# Generated by Django 6.0.2 on 2026-02-05 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_created_at_alter_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('design', 'Graphic Design'), ('printing', 'Printing'), ('branding', 'Branding'), ('apparel', 'Apparel')], default='design', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='design', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
