# Generated by Django 6.0.2 on 2026-02-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_category_portfolio_client_portfolio_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
