# Generated by Django 6.0.2 on 2026-02-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('hear_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
