# Generated by Django 6.0.2 on 2026-02-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quoterequest_delete_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='budget',
            field=models.CharField(choices=[('under-100k', 'Under 100,000 RWF'), ('100k-250k', '100,000 - 250,000 RWF'), ('250k-500k', '250,000 - 500,000 RWF'), ('500k-1m', '500,000 - 1,000,000 RWF'), ('over-1m', 'Over 1,000,000 RWF'), ('flexible', 'Flexible/Not Sure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('google', 'Google Search'), ('social-media', 'Social Media'), ('friend', 'Friend/Referral'), ('previous-client', 'Previous Client'), ('advertisement', 'Advertisement'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='project_type',
            field=models.CharField(choices=[('logo', 'Logo Design'), ('business-cards', 'Business Cards'), ('brochures', 'Brochures/Flyers'), ('banners', 'Banners/Posters'), ('tshirts', 'T-Shirts/Apparel'), ('vehicle', 'Vehicle Branding'), ('packaging', 'Packaging Design'), ('website', 'Website Graphics'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='service_type',
            field=models.CharField(choices=[('design', 'Graphic Design'), ('printing', 'Printing Services'), ('branding', 'Branding & Identity'), ('apparel', 'Apparel Printing'), ('signage', 'Signage & Banners'), ('multiple', 'Multiple Services')], max_length=50),
        ),
    ]
